version: '3'

services:
  db:
    build: db/
    container_name: db
    ports:
      - 3306:3306

  vts:
    build: vts/
    container_name: vts-server
    volumes:
      - "./vts/configure.json:/opt/MF/MF_VTS/web/configure-bak.json"
    ports:
      - 8080:8080
  dkr:
    image: docker
    privileged: true
    working_dir: "/dkr"
    volumes:
      - ".:/dkr"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - db
    command: docker exec -it db /bin/bash mysql
