version: '3'

services:
  db:
    build: db/
    container_name: db
    ports:
      - 3306:3306

  dkr:
    image: docker
    privileged: true
    working_dir: "/dkr"
    volumes:
      - ".:/dkr"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - db
    command: docker exec -it db /bin/bash mysql
